### ISSUE TITLE
How to understand section 3.5 of the article（3.5Deciphered LSTM Internal Signals）

### ISSUE THREAD

**Issue by linbingkong** [oreopie/hydro-interpretive-dl#1]
Thanks open source for great articles and code.Limited personal ability and inability to understand the interpretation of Figure 9 in Section 3.5, in the third column of each graph, how to distinguish which series represent temperature and which series represent precipitation
![image](https://user-images.githubusercontent.com/44971418/156092594-9c7ff233-0a3f-4af5-8562-8cb2d05aa55b.png)
![image](https://user-images.githubusercontent.com/44971418/156093023-c4a1bf0f-63cc-4feb-afac-73b94417991c.png)

Based on Figure 9 how these conclusions were reached, a more detailed explanation is desired

Thank you

**Comment by oreopie** [comment]
Hi @linbingkong, 

Sorry for the late reply. The third column of Figure 9 is to illustrate the difference between LSTM internals about how information was gained and what was actually kept at each time step to predict different types of floods. Rather than separating the contributions of inputs, the method only evaluates the aggregate contribution of each time step. 

I don't think it is easy to say which series represents which input, since the aggregated contribution is a complex function of inputs (Equations 1 and 9 in the paper), but we could observe correlations between some series and inputs. For example, in Figure 9a-x, the proportion to be retained in one unit is relevant to the magnitude of precipitation in latter steps (but note that we didn't claim the series represents the amount of precipitation). 

Overall, the goal of Figure 9 is to demonstrate and contrast the memory mechanisms of LSTMs for runoff prediction (in some cases information was retained to reflect a "long-term"  impact of drivers to hydrological response, while in some cases, only recent information was used, and importantly, the forgetting mechanism has played a role in controlling these).

Hope the clarification helps.

**Comment by linbingkong** [comment]
Thank you very much for taking the time out of your busy schedule to answer.Your clarification helped me a lot to understand.I should combine the two interpretive approaches in the article to understand flood attribution, the two approaches are not independent.

**Comment by linbingkong** [comment]
> ry much for taking the time out of your busy schedule to answer.Your clarification helped me a lot to understand.I should combine the two interpretive approac



> Hi @linbingkong,
> 
> Sorry for the late reply. The third column of Figure 9 is to illustrate the difference between LSTM internals about how information was gained and what was actually kept at each time step to predict different types of floods. Rather than separating the contributions of inputs, the method only evaluates the aggregate contribution of each time step.
> 
> I don't think it is easy to say which series represents which input, since the aggregated contribution is a complex function of inputs (Equations 1 and 9 in the paper), but we could observe correlations between some series and inputs. For example, in Figure 9a-x, the proportion to be retained in one unit is relevant to the magnitude of precipitation in latter steps (but note that we didn't claim the series represents the amount of precipitation).
> 
> Overall, the goal of Figure 9 is to demonstrate and contrast the memory mechanisms of LSTMs for runoff prediction (in some cases information was retained to reflect a "long-term" impact of drivers to hydrological response, while in some cases, only recent information was used, and importantly, the forgetting mechanism has played a role in controlling these).
> 
> Hope the clarification helps.

Thank you very much for taking the time out of your busy schedule to answer.Your clarification helped me a lot to understand.I should combine the two interpretive approaches in the article to understand flood attribution, the two approaches are not independent.
